### ISSUE TITLE
Getting undefined reference to 'hid_get_report descriptor' and 'hid_get_device_info' when compiling/linking test.c

### ISSUE THREAD

**Issue by ajdalessio** [libusb/hidapi#665]
Hi, I've installed hidapi-libusb (sudo apt install libhidapi-dev) and downloaded include file (hidapi.h) and test.c code. When compiling as follows:

gcc -o test.bin test.c -lhidapi-libusb

I get "undefined reference to 'hid_get_report descriptor'" and "undefined reference to 'hid_get_device_info' " errors.

I'm working on an Ubuntu 22.04.4 LTS system.

Which are the possible cause? Thanks for your help!

AD

**Comment by Youw** [comment]
The header you've downloaded is from a different version than the binary you've installed.
When you've installed the libhidapi-dev - the header is installed in the system as well - you should use that one.
